name: Terraform CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write        # Needed for Azure OIDC
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:

      # 🌩️ Azure OIDC credentials
      ARM_USE_OIDC: true
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -reconfigure -upgrade
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Validate
        run: terraform fmt -check && terraform validate
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  apply:
    name: Terraform Apply (requires approval)
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production          # Approval gate before apply
      url: https://portal.azure.com

    env:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -reconfigure -upgrade
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  destroy:
    name: Terraform Destroy (requires approval)
    runs-on: ubuntu-latest
    needs: apply
    environment:
      name: destroy-approval      # Approval gate before destroy
      url: https://portal.azure.com

    env:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -reconfigure -upgrade
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}