name: Terraform CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write        # Needed for Azure OIDC
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      # 🪣 Backend credentials (secret-based)
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # ☁️ OIDC credentials (short-lived)
      ARM_USE_OIDC: true
      ARM_OIDC_CLIENT_ID: ${{ secrets.ARM_OIDC_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_OIDC_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Validate Azure Login
        run: |
          echo "🔎 Validating Azure OIDC authentication..."
          az account show
          echo "✅ Azure OIDC authentication successful!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (Azure backend)
        run: |
          terraform init \
            -reconfigure \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=tfstatecpelayostorage" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="client_id=${{ env.ARM_CLIENT_ID }}" \
            -backend-config="client_secret=${{ env.ARM_CLIENT_SECRET }}" \
            -backend-config="tenant_id=${{ env.ARM_TENANT_ID }}" \
            -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Validate
        run: terraform fmt -check && terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  apply:
    name: Terraform Apply (requires approval)
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
      url: https://portal.azure.com

    env:
      # 🪣 Backend credentials
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # ☁️ OIDC credentials
      ARM_USE_OIDC: true
      ARM_OIDC_CLIENT_ID: ${{ secrets.ARM_OIDC_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_OIDC_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Validate Azure Login
        run: |
          echo "🔎 Validating Azure OIDC authentication..."
          az account show
          echo "✅ Azure OIDC authentication successful!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (Azure backend)
        run: |
          terraform init \
            -reconfigure \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=tfstatecpelayostorage" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="client_id=${{ env.ARM_CLIENT_ID }}" \
            -backend-config="client_secret=${{ env.ARM_CLIENT_SECRET }}" \
            -backend-config="tenant_id=${{ env.ARM_TENANT_ID }}" \
            -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}"

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  destroy:
    name: Terraform Destroy (requires approval)
    runs-on: ubuntu-latest
    needs: apply
    environment:
      name: destroy-approval
      url: https://portal.azure.com

    env:
      # 🪣 Backend credentials
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # ☁️ OIDC credentials
      ARM_USE_OIDC: true
      ARM_OIDC_CLIENT_ID: ${{ secrets.ARM_OIDC_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_OIDC_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Validate Azure Login
        run: |
          echo "🔎 Validating Azure OIDC authentication..."
          az account show
          echo "✅ Azure OIDC authentication successful!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (Azure backend)
        run: |
          terraform init \
            -reconfigure \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=tfstatecpelayostorage" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="client_id=${{ env.ARM_CLIENT_ID }}" \
            -backend-config="client_secret=${{ env.ARM_CLIENT_SECRET }}" \
            -backend-config="tenant_id=${{ env.ARM_TENANT_ID }}" \
            -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve